-- 客户等级
ALTER TABLE customers ADD COLUMN IF NOT EXISTS tier VARCHAR(20) NOT NULL DEFAULT 'normal';
ALTER TABLE customers ADD COLUMN IF NOT EXISTS sales_person VARCHAR(100);

-- 供应商评估
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS rating DECIMAL(3,1) DEFAULT 0;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS on_time_rate DECIMAL(5,2) DEFAULT 0;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS quality_rate DECIMAL(5,2) DEFAULT 0;
